// Assembly Microsoft.SharePointOnline.CAF.CustomRules, Version 13.3.2.0
[assembly: System.Reflection.AssemblyTitle("SharePointCustomRules")]
[assembly: System.Reflection.AssemblyDescription("SharePointCustomRules")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("MSOCAF")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 Microsoft Corporation 2010")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("26a5996e-aed8-48ce-9b1a-a19b2906ba9d")]
[assembly: System.Reflection.AssemblyFileVersion("13.3.2.0")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.DisableOptimizations | System.Diagnostics.DebuggableAttribute.DebuggingModes.EnableEditAndContinue | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | System.Diagnostics.DebuggableAttribute.DebuggingModes.Default)]

